id: I7A79CC95
initial_creation_type: ebook
source_metadata:
  id: SHE-CHE-01
  title: ༄༅། །ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཆོས་སྐོར།
  author: མཛད་པ་པོ། འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
    ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེ། འཇམ་དབྱངས་མཁྱེན་བརྩེ་ཆོས་ཀྱི་བློ་གྲོས།
    མཁན་ཆེན་བཀྲ་ཤིས་འོད་ཟེར། ལས་རབ་གླིང་པ། དིལ་མགོ་མཁྱེན་བརྩེ་རིན་པོ་ཆེ།
  authors: &id001
  - མཛད་པ་པོ། འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས། ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེ།
    འཇམ་དབྱངས་མཁྱེན་བརྩེ་ཆོས་ཀྱི་བློ་གྲོས། མཁན་ཆེན་བཀྲ་ཤིས་འོད་ཟེར། ལས་རབ་གླིང་པ།
    དིལ་མགོ་མཁྱེན་བརྩེ་རིན་པོ་ཆེ།
  sku: SHE-CHE-01
  cover: CHETSUN-Cover-authornames.jpg
  volume: {}
ebook_metadata:
  title: ༄༅། །ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཆོས་སྐོར།
  authors: *id001
  sku: SHE-CHE-01
  cover: CHETSUN-Cover-authornames.jpg
layers:
- Author
- BookTitle
- Chapter
- Commentary
- Sabche
- Yigchung
